### ISSUE TITLE
Support for posting of content

### ISSUE THREAD

**Issue by markhofmann** [pvdlg/diffbot-java-sdk#2]
Please implement support to post content directly to diffbot as described here:
https://www.diffbot.com/dev/docs/article/#posting

Thanks :)

**Comment by pvdlg** [comment]
Hi,
ok I can implement it, however my time is very limited these days...It might take a while...

**Comment by markhofmann** [comment]
Thanks for coming back on that. Actually, since we also required to use version 3 of diffbot I now implemented my own little API.
Cheers,
Mark

**Comment by pvdlg** [comment]
Maybe if I have time I'll make the changes to work with the v3 API.
You can also check the official Diffbot Java SDK released recently: https://github.com/diffbot/diffbot-java-client.
